In [9]:
import sys
sys.path.append("../src")

from analyzer import *

In [11]:
import numpy as np
import pandas as pd

df = pd.read_csv("../data/student_scores.csv")

scores = df.iloc[:,1:].values

student_avg = student_average(scores)

print(student_avg)

[75.75 88.5  52.5  91.25 68.75 85.5  73.75 90.25 58.75 86.25 77.75 93.
 50.   85.   69.   79.75 63.25 88.5  72.   93.5  55.25 82.75 67.75 88.
 48.5  83.5  76.25 91.5  59.25 87.25 73.5  94.5  51.5  80.5  67.5  90.5
 55.5  86.5  78.25 91.5  63.5  85.5  70.5  95.5  46.5  81.5  74.5  88.75
 59.5  83.5  77.75 90.5  52.5  87.5  69.5  93.5  56.5  83.5  75.5  91.5
 61.5  88.5  79.5  93.75 47.5  86.75 72.5  89.5  64.5  82.5  76.5  95.5
 50.5  84.5  68.5  92.5  58.5  87.25 73.5  90.5  55.5  81.5  79.25 94.5
 62.5  87.5  70.5  91.5  49.5  83.5 ]


## Import Libraries and Load Dataset 

In [21]:
import numpy as np
import pandas as pd
import os

path = "../data/student_scores.csv"
df = pd.read_csv(path)


## Convert to NumPy Arrays

In [9]:
scores = df.iloc[:,1:].values
names = df["Name"].values
print(scores)

[[78 82 69 74]
 [88 91 85 90]
 [45 55 60 50]
 [92 89 94 90]
 [65 70 68 72]
 [85 78 92 87]
 [72 80 65 78]
 [91 88 89 93]
 [58 62 55 60]
 [83 90 87 85]
 [77 74 81 79]
 [94 92 95 91]
 [49 52 48 51]
 [86 84 88 82]
 [68 71 67 70]
 [79 83 76 81]
 [62 67 64 60]
 [89 86 91 88]
 [71 69 73 75]
 [93 95 92 94]
 [54 58 56 53]
 [82 85 80 84]
 [66 70 68 67]
 [87 90 89 86]
 [48 50 47 49]
 [84 81 86 83]
 [76 78 74 77]
 [91 93 90 92]
 [59 61 57 60]
 [88 87 89 85]
 [73 75 72 74]
 [95 94 96 93]
 [51 53 52 50]
 [80 82 79 81]
 [67 66 69 68]
 [90 92 91 89]
 [55 57 54 56]
 [86 88 85 87]
 [78 76 80 79]
 [92 91 93 90]
 [63 65 62 64]
 [85 84 87 86]
 [70 72 71 69]
 [94 96 95 97]
 [46 48 45 47]
 [81 83 82 80]
 [74 73 75 76]
 [89 87 88 91]
 [60 59 61 58]
 [83 85 84 82]
 [77 79 78 77]
 [90 89 92 91]
 [52 54 51 53]
 [87 86 88 89]
 [69 71 70 68]
 [93 95 94 92]
 [56 58 55 57]
 [84 82 85 83]
 [75 77 76 74]
 [91 93 90 92]
 [61 63 60 62]
 [88 90 87 89]
 [79 81 78 80]
 [94 92 95 94]
 [47 49 46 48]
 [86 88 86 87]
 [72 74 73

## Student Average Score

In [10]:
student_avg = np.mean(scores, axis=1)

for name, avg in zip(names, student_avg):
    print(name, avg)

Aman 75.75
Riya 88.5
Rahul 52.5
Sneha 91.25
Arjun 68.75
Priya 85.5
Vikram 73.75
Neha 90.25
Karan 58.75
Divya 86.25
Rohit 77.75
Anita 93.0
Sameer 50.0
Pooja 85.0
Mohan 69.0
Sita 79.75
Raj 63.25
Kavya 88.5
Deepak 72.0
Lakshmi 93.5
Vijay 55.25
Meera 82.75
Amit 67.75
Shalini 88.0
Naveen 48.5
Ruchi 83.5
Sunil 76.25
Tara 91.5
Prakash 59.25
Geeta 87.25
Suresh 73.5
Madhu 94.5
Rakesh 51.5
Nisha 80.5
Bharat 67.5
Kiran 90.5
Arvind 55.5
PoojaK 86.5
Dev 78.25
Swati 91.5
Manish 63.5
Rekha 85.5
Jai 70.5
Uma 95.5
Santosh 46.5
Leela 81.5
Hari 74.5
Chitra 88.75
Baldev 59.5
Radha 83.5
Gopal 77.75
Seema 90.5
Ashok 52.5
Veena 87.5
Ravi 69.5
Indira 93.5
Yash 56.5
Mala 83.5
Kunal 75.5
Sangeeta 91.5
Pankaj 61.5
Alka 88.5
Vikas 79.5
Reena 93.75
Dinesh 47.5
Suman 86.75
Ajay 72.5
Kusum 89.5
Naresh 64.5
Baby 82.5
Om 76.5
Lata 95.5
Raju 50.5
Nitu 84.5
Suraj 68.5
Pinky 92.5
Vineet 58.5
Renu 87.25
Sanjay 73.5
Tina 90.5
Mukesh 55.5
Kavita 81.5
Bipin 79.25
Shobha 94.5
Anil 62.5
Jyoti 87.5
Ramesh 70.5
Sunita 91.5
Visha

## Top Performer

In [11]:
top_index = np.argmax(student_avg)

print("Top Student:", names[top_index])
print("Average Score:", student_avg[top_index])

Top Student: Uma
Average Score: 95.5


## Subject-wise Average

In [12]:
subject_avg = np.mean(scores, axis=0)

subjects = ["Math","Science","English","History"]

for sub, avg in zip(subjects, subject_avg):
    print(sub, avg)

Math 75.93333333333334
Science 77.21111111111111
English 76.33333333333333
History 76.31111111111112


## Hardest Subject

In [13]:
hardest = subjects[np.argmin(subject_avg)]

print("Hardest Subject:", hardest)

Hardest Subject: Math


## Pass / Fail Analysis

In [14]:
pass_mask = scores >= 50

pass_count = np.sum(pass_mask, axis=1)

print(pass_count)

fail_students = names[pass_count < 4]

print("Students needing improvement:", fail_students)

[4 4 3 4 4 4 4 4 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 0 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 0 4 4 4 4 4 4 4 3 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 4]
Students needing improvement: ['Rahul' 'Sameer' 'Naveen' 'Santosh' 'Dinesh' 'Raju' 'Vishal']


## Student Ranking

In [15]:
rank = np.argsort(-student_avg)

print("Student Ranking")

for i in rank:
    print(names[i], student_avg[i])

Student Ranking
Uma 95.5
Lata 95.5
Madhu 94.5
Shobha 94.5
Reena 93.75
Lakshmi 93.5
Indira 93.5
Anita 93.0
Pinky 92.5
Sunita 91.5
Swati 91.5
Tara 91.5
Sangeeta 91.5
Sneha 91.25
Kiran 90.5
Seema 90.5
Tina 90.5
Neha 90.25
Kusum 89.5
Chitra 88.75
Kavya 88.5
Riya 88.5
Alka 88.5
Shalini 88.0
Jyoti 87.5
Veena 87.5
Renu 87.25
Geeta 87.25
Suman 86.75
PoojaK 86.5
Divya 86.25
Priya 85.5
Rekha 85.5
Pooja 85.0
Nitu 84.5
Mala 83.5
Radha 83.5
Meena 83.5
Ruchi 83.5
Meera 82.75
Baby 82.5
Leela 81.5
Kavita 81.5
Nisha 80.5
Sita 79.75
Vikas 79.5
Bipin 79.25
Dev 78.25
Gopal 77.75
Rohit 77.75
Om 76.5
Sunil 76.25
Aman 75.75
Kunal 75.5
Hari 74.5
Vikram 73.75
Sanjay 73.5
Suresh 73.5
Ajay 72.5
Deepak 72.0
Ramesh 70.5
Jai 70.5
Ravi 69.5
Mohan 69.0
Arjun 68.75
Suraj 68.5
Amit 67.75
Bharat 67.5
Naresh 64.5
Manish 63.5
Raj 63.25
Anil 62.5
Pankaj 61.5
Baldev 59.5
Prakash 59.25
Karan 58.75
Vineet 58.5
Yash 56.5
Mukesh 55.5
Arvind 55.5
Vijay 55.25
Ashok 52.5
Rahul 52.5
Rakesh 51.5
Raju 50.5
Sameer 50.0
Vishal 49.5
Nav

## Grade Calculation (Vectorization)

In [16]:
grades = np.where(student_avg >= 90, "A",
         np.where(student_avg >= 80, "B",
         np.where(student_avg >= 70, "C",
         np.where(student_avg >= 60, "D", "F"))))

for name, grade in zip(names, grades):
    print(name, grade)

Aman C
Riya B
Rahul F
Sneha A
Arjun D
Priya B
Vikram C
Neha A
Karan F
Divya B
Rohit C
Anita A
Sameer F
Pooja B
Mohan D
Sita C
Raj D
Kavya B
Deepak C
Lakshmi A
Vijay F
Meera B
Amit D
Shalini B
Naveen F
Ruchi B
Sunil C
Tara A
Prakash F
Geeta B
Suresh C
Madhu A
Rakesh F
Nisha B
Bharat D
Kiran A
Arvind F
PoojaK B
Dev C
Swati A
Manish D
Rekha B
Jai C
Uma A
Santosh F
Leela B
Hari C
Chitra B
Baldev F
Radha B
Gopal C
Seema A
Ashok F
Veena B
Ravi D
Indira A
Yash F
Mala B
Kunal C
Sangeeta A
Pankaj D
Alka B
Vikas C
Reena A
Dinesh F
Suman B
Ajay C
Kusum B
Naresh D
Baby B
Om C
Lata A
Raju F
Nitu B
Suraj D
Pinky A
Vineet F
Renu B
Sanjay C
Tina A
Mukesh F
Kavita B
Bipin C
Shobha A
Anil D
Jyoti B
Ramesh C
Sunita A
Vishal F
Meena B


## Standard Deviation

In [17]:
np.std(scores, axis=0)

array([14.38038788, 13.57570906, 14.53883688, 14.16226947])

## Highest score in each subject

In [18]:
np.max(scores, axis=0)

array([95, 97, 96, 97])

## Lowest score in each subject

In [19]:
np.min(scores, axis=0)

array([45, 48, 45, 47])